package org.wintrisstech.erik.iaroc;

public enum RobotState {
	STARTING,
	GOING_FORWARD,
	GOING_STRAIGHT_FORWARD,
	TURNING_RIGHT_AFTER_FRONT_BUMP,
	TURNING_RIGHT_AFTER_LEFT_BUMP,
	TURNING_LEFT,
	BUMPING, 
	GOING_BACKWARD,
	BUMPING_LEFT,
	BUMPING_RIGHT,
	NEAR_HOME_BASE,
	HOMING,
}
